Update 2-erc20-in-game-token.adoc
skalenetwork/docs.skale.network pull request #203
Opened 2023-07-26 05:12 UTC by SKALE-jace

Fixed SPDX License typo

2023-07-26 05:59 UTC, TheGreatAxios approved these changes
Thanks for fixing

2023-07-26 15:12 UTC, cstrangedk requested changes

2023-07-27 20:26 UTC, TheGreatAxios approved these changes

2023-07-27 20:27 UTC, SKALE-jace commented on components/recipes/modules/ROOT/pages/solidity/2-erc20-in-game-token.adoc
> +     * @param amount The amount of tokens to send the to the address
removed

2023-09-01 20:15 UTC, TheGreatAxios approved these changes

2024-01-24 20:47 UTC, closed without merging